In [14]:
import torch
import numpy as np
import pandas as pd
import os
import struct
from torch import nn

In [22]:
def read_idx3_ubyte(idx3_ubyte_file):
    with open(idx3_ubyte_file, 'rb') as f:
        magic, num_images, rows, cols = struct.unpack('>IIII', f.read(16))
        images = np.fromfile(f, dtype=np.uint8).reshape(num_images, rows, cols)
    return images

def read_idx1_ubyte(idx1_ubyte_file):
    with open(idx1_ubyte_file, 'rb') as f:
        magic, num_labels = struct.unpack('>II', f.read(8))
        labels = np.fromfile(f, dtype=np.uint8)  
    return labels



In [23]:
images = read_idx3_ubyte('train-images.idx3-ubyte')
labels =read_idx1_ubyte('train-labels.idx1-ubyte')
images2 = read_idx3_ubyte('t10k-images.idx3-ubyte')
labels2 =read_idx1_ubyte('t10k-labels.idx1-ubyte')

In [17]:
images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [24]:
images2

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [25]:
labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [19]:
images_reshaped = images.reshape(images.shape[0], -1)  # 将每个图像重塑(flatten)为一行

df = pd.DataFrame(images_reshaped)

df['label'] = labels


In [26]:
images2_reshaped = images2.reshape(images2.shape[0], -1)  # 将每个图像重塑(flatten)为一行

df2 = pd.DataFrame(images2_reshaped)

df2['label'] = labels2

In [20]:
df

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4      0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...   .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
59995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
59996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
59997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
59998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
59999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

       782  783  label  
0        0    0      5  
1        0    0      0  
2        0    0      4  
3        0    0      1  
4        0    0      9  
...    ...  ...    ...  
59995    0    0      8  
59996    0    0      3  
59997    0    0      5  
59998    0    0      6  
59999    0    0      8  

[60000 rows x 785 columns]

In [21]:
df.to_csv('train.csv', index=False)

In [27]:
df2

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...  .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
9995  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9996  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9997  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9998  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9999  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   

      782  783  label  
0       0    0      7  
1       0    0      2  
2       0    0      1  
3       0    0      0  
4       0    0      4  
...   ...  ...    ...  
9995    0    0      2  
9996    0    0      3  
9997    0    0      4  
9998    0    0      5  
9999    0    0      6  

[10000 rows x 785 columns]

In [28]:
df2.to_csv('test.csv', index=False)